name: Deploy code to godaddy

on:
  # Trigger when code is pushed to the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 'Create env file'
        run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          cat .env

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.GODADDY_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.GODADDY_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to GoDaddy
        run: rsync -avz ./ ${{ secrets.GODADDY_SSH_USERNAME }}@${{ secrets.GODADDY_SSH_HOST }}:/home/dancingpaul1/public_html/missjennyshotsauce.com/public_html/wp-content/themes/salient-child --exclude '.git/' --exclude '.github/'
